version: "3"

tasks:
  default:
    cmds:
      - task: fmt
      - task: lint
      - task: install

  build:
    cmds:
      - go build -v ./...

  install:
    cmds:
      - task: build
      - go install -v ./...

  lint:
    cmds:
      - golangci-lint run

  fmt:
    cmds:
      - gofmt -s -w -e .

  test:
    cmds:
      - go test -v -coverprofile=coverage.out -timeout=120s -parallel=10 ./...

  cover:
    deps:
      - test
    cmds:
      - go tool cover -html=coverage.out
