version: "3"

tasks:
  default:
    cmds:
      - task: fmt
      - task: lint
      - task: install

  build:
    cmds:
      - go build -v ./...

  install:
    cmds:
      - task: build
      - go install -v ./...

  lint:
    cmds:
      - golangci-lint run

  fmt:
    cmds:
      - gofmt -s -w -e .

  test:
    cmds:
      - go test -v -coverprofile=coverage.out -timeout=120s -parallel=10 ./...

  cover:
    deps:
      - test
    cmds:
      - go tool cover -html=coverage.out

  check-docs:
    desc: Check for missing documentation in Go files
    cmds:
      - |
        for file in $(find . -name "*.go" -not -path "./vendor/*"); do
          if ! go doc $file | grep -q "^Package\|^FUNCTIONS\|^TYPES"; then
            echo "Missing documentation in $file"
          fi
        done

  docs-server:
    desc: Start a local documentation server
    cmds:
      - go install golang.org/x/tools/cmd/godoc@latest
      - godoc -http=:6060

  mcp-dev:
    desc: Run the modelcontexprotocol inspector
    cmds:
      - npx @modelcontextprotocol/inspector -e OPENAI_API_KEY=$OPENAI_API_KEY go run cmd/mcp/main.go
